export interface Badge {
  type: 'Zone' | 'User' | 'Group' | 'IP Range' | 'Internet';
  value: string;
}

export interface Policy {
  id: string;
  name: string;
  type: 'SPA' | 'SIA' | 'Zone'; 
  accessScope: 'Private' | 'Internet' | 'Hybrid' | 'Zone';
  source: 'Default' | 'User';
  description: string;
  action: 'Allow' | 'Deny';
  status: 'Active' | 'Inactive';
  
  // Access Intent Fields
  identity: string; // Acts as Source Zone for Zone policies
  resource: string; // Acts as Destination Zone for Zone policies
  trustCondition: string; // "None" triggers warning
  
  destination: string; // Detailed destination
  enforcement: 'ZTC Device' | 'Cloud Edge' | 'ZTC + Cloud' | 'Firewall';
  
  // Badge data for view screen
  sourceBadges?: Badge[];
  destinationBadges?: Badge[];
}

export const MOCK_POLICIES: Policy[] = [
  // Zone Based Policies (New)
  {
    id: 'zone-1',
    name: 'Enable IoT devices to access the internet.',
    type: 'Zone',
    accessScope: 'Zone',
    source: 'Default',
    description: 'Allow devices on iot network access to internet',
    action: 'Allow',
    status: 'Active',
    identity: 'IoT',
    resource: 'Internet',
    trustCondition: 'None',
    destination: 'Any',
    enforcement: 'Firewall',
    sourceBadges: [{ type: 'Zone', value: 'IoT' }],
    destinationBadges: [{ type: 'Zone', value: 'Internet' }],
  },
  {
    id: 'zone-2',
    name: 'Allow Guest Network to Internet',
    type: 'Zone',
    accessScope: 'Zone',
    source: 'Default',
    description: 'Allow users on guest network broad access to internet',
    action: 'Allow',
    status: 'Active',
    identity: 'Guest',
    resource: 'Internet',
    trustCondition: 'None',
    destination: 'Any',
    enforcement: 'Firewall',
    sourceBadges: [{ type: 'Zone', value: 'Guest' }],
    destinationBadges: [{ type: 'Zone', value: 'Internet' }],
  },
  {
    id: 'zone-3',
    name: 'Block Guest Network from Internet',
    type: 'Zone',
    accessScope: 'Zone',
    source: 'User',
    description: 'Deny guest network access to internet — conflicts with rule above',
    action: 'Deny',
    status: 'Active',
    identity: 'Guest',
    resource: 'Internet',
    trustCondition: 'None',
    destination: 'Any',
    enforcement: 'Firewall',
    sourceBadges: [{ type: 'Zone', value: 'Guest' }],
    destinationBadges: [{ type: 'Zone', value: 'Internet' }],
  },
  {
    id: 'zone-4',
    name: 'Allow Employee to Guest Zone',
    type: 'Zone',
    accessScope: 'Zone',
    source: 'User',
    description: 'Allow traffic from employee zone to guest zone',
    action: 'Allow',
    status: 'Active',
    identity: 'Employee',
    resource: 'Guest',
    trustCondition: 'None',
    destination: 'Any',
    enforcement: 'Firewall',
    sourceBadges: [{ type: 'Zone', value: 'Employee' }],
    destinationBadges: [{ type: 'Zone', value: 'Guest' }],
  },
  {
    id: 'zone-5',
    name: 'Block Guest to Employee Zone',
    type: 'Zone',
    accessScope: 'Zone',
    source: 'User',
    description: 'Block traffic from guest zone to employee zone',
    action: 'Deny',
    status: 'Active',
    identity: 'Guest',
    resource: 'Employee',
    trustCondition: 'None',
    destination: 'Any',
    enforcement: 'Firewall',
    sourceBadges: [{ type: 'Zone', value: 'Guest' }],
    destinationBadges: [{ type: 'Zone', value: 'Employee' }],
  },
  {
    id: 'zone-def-2',
    name: 'Restrict Guest Zone to Employee Zone',
    type: 'Zone',
    accessScope: 'Zone',
    source: 'Default',
    description: 'Prevents users in Guest Zone from accessing any devices or resources within Employee Zone. Enforces network segmentation between guest and corporate environments.',
    action: 'Deny',
    status: 'Active',
    identity: 'Guest',
    resource: 'Employee',
    trustCondition: 'None',
    destination: 'Any',
    enforcement: 'Firewall',
    sourceBadges: [{ type: 'Zone', value: 'Guest' }],
    destinationBadges: [{ type: 'Zone', value: 'Employee' }],
  },

  // User SPA Policies
  {
    id: 'spa-usr-1',
    name: 'Policy to Access PCI Server',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Access to internal payment processing infrastructure',
    action: 'Allow',
    status: 'Active',
    identity: 'Employees',
    resource: 'payment-gateway.internal',
    trustCondition: 'High Trust',
    destination: 'Any',
    enforcement: 'ZTC Device',
  },
  {
    id: 'spa-usr-2',
    name: 'Policy to Access User Database',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Read-only access to user records for support staff',
    action: 'Allow',
    status: 'Active',
    identity: 'Support Team',
    resource: 'user-db.internal',
    trustCondition: 'Compliant Device',
    destination: 'Any',
    enforcement: 'ZTC + Cloud',
  },
  {
    id: 'spa-usr-3',
    name: 'Permit Access to Internal Wiki',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Company knowledge base and documentation access',
    action: 'Allow',
    status: 'Active',
    identity: 'All Employees',
    resource: 'wiki.internal.company.com',
    trustCondition: 'Managed Device',
    destination: 'Any',
    enforcement: 'ZTC Device',
  },
  {
    id: 'spa-usr-4',
    name: 'Allow Access to Development Servers',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Access to staging and development environments',
    action: 'Allow',
    status: 'Active',
    identity: 'Engineering Team',
    resource: 'dev-servers.internal',
    trustCondition: 'High Trust',
    destination: 'Any',
    enforcement: 'ZTC + Cloud',
  },
  {
    id: 'spa-usr-5',
    name: 'Restrict Access to Finance Systems',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Controlled access to financial applications and data',
    action: 'Allow',
    status: 'Active',
    identity: 'Finance Department',
    resource: 'finance-app.internal',
    trustCondition: 'High Trust',
    destination: 'Any',
    enforcement: 'ZTC Device',
  },
  {
    id: 'spa-usr-6',
    name: 'Grant Access to HR Portal',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Employee self-service and HR management system',
    action: 'Allow',
    status: 'Active',
    identity: 'All Employees',
    resource: 'hr-portal.company.com',
    trustCondition: 'Compliant Device',
    destination: 'Any',
    enforcement: 'Cloud Edge',
  },
  {
    id: 'spa-usr-7',
    name: 'File Server Access - Engineering',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Access to engineering shared drives and repositories',
    action: 'Allow',
    status: 'Active',
    identity: 'Engineering Team',
    resource: 'fileserver-eng.internal',
    trustCondition: 'Managed Device',
    destination: 'Any',
    enforcement: 'ZTC Device',
  },
  {
    id: 'spa-usr-8',
    name: 'CRM System Access',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Salesforce and customer relationship management access',
    action: 'Allow',
    status: 'Inactive',
    identity: 'Sales Team',
    resource: 'crm.company.com',
    trustCondition: 'Compliant Device',
    destination: 'Any',
    enforcement: 'Cloud Edge',
  },
  {
    id: 'spa-usr-9',
    name: 'API Gateway Access',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Access to internal API management and testing tools',
    action: 'Allow',
    status: 'Active',
    identity: 'Developers',
    resource: 'api-gateway.internal',
    trustCondition: 'High Trust',
    destination: 'Any',
    enforcement: 'ZTC + Cloud',
  },
  {
    id: 'spa-usr-10',
    name: 'Database Admin Console',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Production database administration and monitoring',
    action: 'Allow',
    status: 'Active',
    identity: 'Database Admins',
    resource: 'db-admin.internal',
    trustCondition: 'High Trust',
    destination: 'Any',
    enforcement: 'ZTC Device',
  },
  {
    id: 'spa-usr-11',
    name: 'Block Contractor Access to Secrets',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Prevent external contractors from accessing secrets vault',
    action: 'Deny',
    status: 'Active',
    identity: 'Contractors',
    resource: 'secrets.internal',
    trustCondition: 'None',
    destination: 'Any',
    enforcement: 'ZTC Device',
  },
  {
    id: 'spa-usr-12',
    name: 'Email Archive Access',
    type: 'SPA',
    accessScope: 'Private',
    source: 'User',
    description: 'Access to historical email records for compliance',
    action: 'Allow',
    status: 'Active',
    identity: 'Compliance Team',
    resource: 'email-archive.internal',
    trustCondition: 'Managed Device',
    destination: 'Any',
    enforcement: 'Cloud Edge',
  },

  // User SIA Policies
  {
    id: 'sia-usr-1',
    name: 'Social Media - Lunch Only',
    type: 'SIA',
    accessScope: 'Internet',
    source: 'User',
    description: 'Allows social media access during lunch hours',
    action: 'Allow',
    status: 'Inactive',
    identity: 'All Employees',
    resource: 'Social Networking',
    trustCondition: 'None',
    destination: 'Any',
    enforcement: 'Cloud Edge',
    sourceBadges: [{ type: 'User', value: 'All Employees' }],
    destinationBadges: [{ type: 'Internet', value: 'Internet' }],
  },
  {
    id: 'sia-usr-2',
    name: 'Block High Risk Sites',
    type: 'SIA',
    accessScope: 'Internet',
    source: 'User',
    description: 'Block sites with high risk reputation score',
    action: 'Deny',
    status: 'Active',
    identity: 'All Users',
    resource: 'High Risk Sites',
    trustCondition: 'None',
    destination: 'Any',
    enforcement: 'Cloud Edge',
    sourceBadges: [{ type: 'User', value: 'All Users' }],
    destinationBadges: [{ type: 'Internet', value: 'Internet' }],
  },

  // Default Policies (Moved to bottom)
  {
    id: 'spa-def-1',
    name: 'Initial Default SPA Configuration',
    type: 'SPA',
    accessScope: 'Private',
    source: 'Default',
    description: 'Base access policy for verified corporate devices',
    action: 'Allow',
    status: 'Active',
    identity: 'Verified Devices',
    resource: 'Employee Zone',
    trustCondition: 'managed device',
    destination: 'Any',
    enforcement: 'ZTC Device',
  },
  {
    id: 'sia-def-1',
    name: 'Allow All Users to Internet',
    type: 'SIA',
    accessScope: 'Internet',
    source: 'Default',
    description: 'Baseline internet security and threat protection',
    action: 'Allow',
    status: 'Active',
    identity: 'All Users',
    resource: 'Malicious Sites',
    trustCondition: 'basic threat protection',
    destination: 'Any',
    enforcement: 'Cloud Edge',
    sourceBadges: [{ type: 'User', value: 'All Users' }],
    destinationBadges: [{ type: 'Internet', value: 'Internet' }],
  },
];